import type { SaasEntry } from '@/types'

export const mockSaasEntries: SaasEntry[] = [
  {
    id: '1',
    nome: 'Notion AI Writer',
    nicho: 'Productividad',
    modelo_preco: 'Suscripción',
    pais_origen: 'Estados Unidos',
    emoji: '✍️',
    print_url: '',
    link_site: 'https://notion.so',
    link_anuncios: '#',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    nome: 'Lemonsqueezy',
    nicho: 'Pagamentos',
    modelo_preco: 'Comisión',
    pais_origen: 'Estados Unidos',
    emoji: '🍋',
    print_url: '',
    link_site: 'https://lemonsqueezy.com',
    link_anuncios: '#',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    nome: 'Pocketbase',
    nicho: 'Dev Tools',
    modelo_preco: 'One-time',
    pais_origen: 'Bulgaria',
    emoji: '🗄️',
    print_url: '',
    link_site: 'https://pocketbase.io',
    link_anuncios: '#',
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    nome: 'Tally Forms',
    nicho: 'Formularios',
    modelo_preco: 'Freemium',
    pais_origen: 'Bélgica',
    emoji: '📋',
    print_url: '',
    link_site: 'https://tally.so',
    link_anuncios: '#',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '5',
    nome: 'Typefully',
    nicho: 'Redes Sociales',
    modelo_preco: 'Suscripción',
    pais_origen: 'España',
    emoji: '🐦',
    print_url: '',
    link_site: 'https://typefully.com',
    link_anuncios: '#',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: '6',
    nome: 'Plausible',
    nicho: 'Analytics',
    modelo_preco: 'Suscripción',
    pais_origen: 'Estonia',
    emoji: '📈',
    print_url: '',
    link_site: 'https://plausible.io',
    link_anuncios: '#',
    created_at: '2024-02-15T00:00:00Z',
  },
]

export const nichos = [
  'Todos',
  'Productividad',
  'Pagamentos',
  'Dev Tools',
  'Formularios',
  'Redes Sociales',
  'Analytics',
]

export const paises = [
  'Todos',
  'Estados Unidos',
  'Bulgaria',
  'Bélgica',
  'España',
  'Estonia',
]
